Update main.yml
swap to shiv actions

Update main.yml

Update main.yml

Update main.yml

Update main.yml

Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,32 +1,66 @@
-name: Build EXE with PyInstaller
+name: Python Build Matrix
 
-on: [push, pull_request]  # Runs on push and PRs, modify as needed
+on:
+  push:
+    branches: [ "main" ]
+  pull_request:
+    branches: [ "main" ]
 
 jobs:
-  build:
-    runs-on: windows-latest  # Windows runner to build EXE
+  python_build_matrix:
+    strategy:
+      matrix:
+        os: [ubuntu-22.04, windows-2022]
+        version: ["3.12.1", "3.11.7", "3.10.11", "3.9.13"]
 
+    runs-on: ${{ matrix.os }}
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+    - uses: actions/checkout@v4
 
-    - name: Set up Python
-      uses: actions/setup-python@v4
+    - name: Set up Python ${{ matrix.version }}
+      uses: actions/setup-python@v5
       with:
-        python-version: '3.11'  # Change to your Python version
+        python-version: ${{ matrix.version }}
 
-    - name: Install dependencies
+    - name: Verify Python installation
+      run: |
+        python --version
+        which python
+        python -m pip --version
+
+    - name: Install APT Dependencies (Linux)
+      run: |
+        if [ "$RUNNER_OS" == "Linux" ]; then sudo apt update; sudo apt install libasound2-dev -y; fi
+      shell: bash
+
+    - name: Install Dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install pyinstaller
-        pip install -r requirements.txt  # If you have dependencies
+        pip install --upgrade shiv -r requirements.txt
 
-    - name: Build executable
+    - name: Verify shiv installation
       run: |
-        pyinstaller --onefile --windowed main.py --icon=Outlaw-TransparentBackground.ico --add-data "img.png;."
+        pip show shiv
+        # Check if shiv is installed properly
+        if ! command -v shiv &> /dev/null
+        then
+          echo "shiv could not be found"
+          exit 1
+        else
+          echo "shiv is installed"
+        fi
 
-    - name: Upload EXE artifact
+    - name: Build Shiv Zipapp
+      run: |
+        shiv -c main -o frc_dashboard.pyz -r requirements.txt .
+        ls -l  # List files to verify if .pyz file is created
+        # Print the directory content to ensure the .pyz file is in the correct path
+        ls -l ${GITHUB_WORKSPACE}
+
+    - name: Upload Zipapp Artifact
       uses: actions/upload-artifact@v4
       with:
-        name: REEFSCAPE Operator Dashboard.exe
-        path: dist/main.exe
+        name: FRC Dashboard ${{ matrix.os }} For Python v${{ matrix.version }}
+        path: |
+          ${{ github.workspace }}/frc_dashboard.pyz
+        if-no-files-found: warn
